[package]
name = "antimony-core"
version = "0.1.0"
authors = ["Mohammad Samir <me@msamir.me>"]

[dependencies]
rustc-serialize = "0.3.24"
zookeeper = "0.3.0"
clap = "2.26.0"
futures = "0.1.16"
tokio-core = "0.1.9"
tokio-io = "0.1.3"
tokio-uds = "0.1.5"
futures-cpupool = "0.1.6"